### ISSUE TITLE
Failure to load

### ISSUE THREAD

**Issue by lionkeng** [sysgears/apollo-fullstack-starter-kit#1]
Hi! I followed the instructions in README.md, and when I ran `npm start`, and browse localhost:/3000/counter, I see this error in the console log:
![screen shot 2016-09-20 at 2 50 10 pm](https://cloud.githubusercontent.com/assets/1751072/18660213/d4fbf0d6-7f41-11e6-8cd9-161d600cde8b.png)

**Comment by vlasenko** [comment]
Hi!

Seems this is a problem not really of this starter kit, but in apollo client 0.4.16. Hopefully they will fix it soon. For now you can use version 0.4.15 instead.

Replace in package.json
"apollo-client": "^0.4.14"
to
"apollo-client": "0.4.15"

**Comment by lionkeng** [comment]
That fixed it. Thx!
