### ISSUE TITLE
Redux integration

### ISSUE THREAD

**Issue by mitjade** [sysgears/apollo-fullstack-starter-kit#11]
When trying to integrate Redux into my project I keep getting:

> warning.js:36 Warning: React attempted to reuse markup in a container but the checksum was invalid.

Added store in src/server/middleware/website.jsx and src/client/main.jsx like:
```
import { createStore, combineReducers, applyMiddleware, compose } from 'redux';
import TestReducer from '../store/reducers/test_reducers';

const store = createStore(
  combineReducers({
    test: TestReducer,
    apollo: client.reducer(),
  }),
  {}, // initial state
  compose(
    applyMiddleware(client.middleware()),
  )
);
...
<ApolloProvider store={store} ...
```

I presume it has to do with ssr, but can not figure out how to solve this.

**Comment by vlasenko** [comment]
Well, I don't quite see relation of your question to this project :) I'm not sure what is going wrong with SSR in your project, but at least full source code is needed and reproduction steps to debug and answer your question. Or, as an option, you can for this project, add redux store as you do in your project and trigger SSR problem, then I will be able to help.

**Comment by mitjade** [comment]
https://github.com/mitjade/apollo-fullstack-starter-kit

**Comment by vlasenko** [comment]
Because you are using custom Redux store, on client-side you should initialize it with Apollo query results, e.g.  `__APOLLO_STATE__`. Previously `__APOLLO_STATE__` was pushed as param inside createApolloClient. With custom Redux store you should provide data from __APOLLO_STATE__ into your store instead, upon creation on client-side.

https://github.com/mitjade/apollo-fullstack-starter-kit/pull/1

**Comment by mitjade** [comment]
You are a life saver. Thanks a million.

**Comment by vlasenko** [comment]
You are welcome :)

**Comment by mitjade** [comment]
Did minor code cleanup on https://github.com/mitjade/apollo-fullstack-starter-kit, in case anyone else would find this useful.
