### ISSUE TITLE
General file structure 

### ISSUE THREAD

**Issue by GiladShoham** [sysgears/apollo-fullstack-starter-kit#112]
Hi,

Currently, the files/folder structure is to have a folder per file type, I mean for example resolvers, graphqls, and subscription.
For my opinion when a project become bigger it's much more convenient to have folders by feature then different file types.
For example in this case to have:
post folder and inside to have post.graphql post.subscription post.resolvers and so on.
I think it's much better.

Of course, anyone using this starter kit can easily change it, but it makes it much harder then to actively getting new stuff from upstream (like I do on regular basis for my project).

Would like to hear your opinion about it.

@vlasenko  @mitjade

**Comment by vlasenko** [comment]
Thanks @GiladShoham. I agree, folder per feature is the best approach in my opinion and it's the most convenient to easily add and remove features to the project, both in the form of examples from this starter kit and project-specific features as well.

**Comment by GiladShoham** [comment]
@vlasenko 
So let's change the structure:)
(I didn't change my own structure only to easily keep getting updates)

**Comment by vlasenko** [comment]
@GiladShoham Yeah, I'm also having issues with keeping in sync this starter kit with my projects, so I'm all for per-feature structure and perhaps support for overriding `webpack.config.js` with project-specific config, so that I can take `webpack.config.js` and `webpack.run.js` into my projects as is. This is of course, very minimal improvements to make this kit easy to keep in sync with real projects, much more improvements possible.

**Comment by josephdburdick** [comment]
So uhh, yeah, just lemme know when I should update from upstream, guys. :wink:

**Comment by mitjade** [comment]
I apologise for not doing this correctly in the first place for the post example. I had some problems figuring out how to do this correctly, so I simplified it a bit to make it work in the first place and now I'm trying to come up with the correct approach, while all of you have to deal with trying to keep your projects all up to date.

So what would then ideally be the structure for let's say post example:

`src -> post -> assets`
`src -> post -> database -> migrations`
`src -> post -> database -> seed`
`src -> post -> server -> api`
`src -> post -> server -> sql`
`src -> post -> ui -> components`
`src -> post -> ui -> containers`
`src -> post -> ui -> graphql`
`src -> post -> ui -> reducers`

Do we completely extract the `counter` example in it's own folder as well?

Do you agree with my attempt of `index.js` for `schema`, `resolvers`, `subscriptions`, `resucers` (intended to do it for this a well), when you have to link all features together?
Let's first come up with the structure we all agree upon and then we can make one PR to do this the right way.

**Comment by mitjade** [comment]
I also forgot `src -> server -> middleware -> graphql.js`. How do we separate this per feature?

**Comment by vlasenko** [comment]
@mitjade I need to think about the structure. Right now it looks like as too many folders per feature, but maybe thats okay, I'm not 100% sure.

**Comment by mitjade** [comment]
I guess this depends how bit the feature will be. I it is a small one and you have one file per folder it is just annoying, but when you have 5 or more per folder, then this quickly becomes handy.

**Comment by vlasenko** [comment]
@mitjade Yes, I agree. Okay, let's do it with the folder structure as you described. 

> I also forgot src -> server -> middleware -> graphql.js. How do we separate this per feature?
Maybe have something like 'export function createGraphQLContext() { return new Count(); }' inside each feature say in file like `post -> index.js` and then in  `src -> server -> middleware -> graphql.js` and in other places where we need to get feature list use `require.context` ?

**Comment by mitjade** [comment]
I can try to prepare something in the evening. Would love to hear the opinion of anyone else that has some structure already in place, with possible suggestions on how to change / improve proposed.

**Comment by mitjade** [comment]
Probably we need also a general folder to put features in.

would `src -> modules -> post` be a ok?

**Comment by vlasenko** [comment]
@mitjade Yes, fine with me

**Comment by mitjade** [comment]
I started a PR for this #114.

**Comment by GiladShoham** [comment]
I think we should keep the server/ui separation and create features folder in each one of them.
This will leave us with a reasonable place for all the common stuff like middlewares and not feature specific files.
So it should be something like:
(--> represents a folder 
-- represents a file)

The client part inner structure I didn't change much (only add features folder above).
```
src -> server
      -> aseets
      -> database
           --seed.js
      -> middleware
          --graphiql.js
          --graphql.js
          --website.jsx
       -- schema.js
       -- subscription.js
       -- api_server.js
       -- index.js
       -> features
	  -> post
		-- post.schema.graphql
		-- post.resolvers.js
		-- post.subscriptions.js
		-- post.seed.js
		-- post.migration.js
       
...

src -> ui -> features -> post -> components
src -> ui -> features -> post -> containers
src -> ui -> features -> post -> graphql
src -> ui -> features -> post -> reducers
```

**Comment by mitjade** [comment]
@GiladShoham Thank you for your comments.

I am ok with both approaches. Maybe keeping server and ui separate is even better, if later you would need to start a separate project that only depends on the server part. Personally I prefer `modules` over `features`, but ether is fine with me. Maybe I would stick with `post_...`, since the rest of the kit uses this convention.

@vlasenko Please comment what you think.

**Comment by vlasenko** [comment]
@mitjade Okay, Let me propose yet another schema:
`src -> ui -> core`
`src -> ui -> core -> index.jsx`
`src -> ui -> core -> main.jsx`
`src -> ui -> favicon -> assets`
`src -> ui -> post -> index.jsx // If the feature has initial view it should go here`
`src -> ui -> post -> post_add.jsx`
`src -> ui -> post -> post_edit.jsx`
`...`
`src -> ui -> post -> assets`
`src -> ui -> post -> reducers`
`src -> ui -> post -> graphql`
`src -> ui -> counter`

`src -> server -> core -> index.js`
`src -> server -> core -> api_server.js`
`src -> server -> core -> middleware -> ...`
`src -> server -> post -> index.js    // Expose some 'feature API' here to be used by core or other server features`
`src -> server -> post -> graphqls`
`src -> server -> post -> resolvers`
`src -> server -> post -> subscriptions`
`src -> server -> post -> migrations`
`src -> server -> post -> seeds`
`src -> server -> post -> orm`

The idea is to split UI and backend on a per-feature basis, with `core` as an entry-feature which will dynamically import all the other features via `require.context`. Each feature on a back-end part might expose some 'feature API' to help importing and adding it to `core`.

**Comment by mitjade** [comment]
@vlasenko I like your proposal. Will try to implement this in `modules_restructure` branch. But do not jet know when, since I am busy with other stuff currently. Hopefully over the weekend.

**Comment by mitjade** [comment]
@vlasenko I guess I do not quite understand the part of dynamically import all the other features via `require.context`. Could you maybe make a branch and create an example off this with core and counter and I will then try to follow along with restructuring the post `feature`.

**Comment by vlasenko** [comment]
@mitjade Sure, will do!

**Comment by vlasenko** [comment]
@mitjade I have done initial work of modularizing this starter kit in `modularize` branch here:
https://github.com/sysgears/apollo-fullstack-starter-kit/tree/modularize

The tracking Pull Request for this branch is here:
https://github.com/sysgears/apollo-fullstack-starter-kit/pull/118

Post and counter have been moved into separate `modules`. To fully remove `counter` module from project one should delete `client/modules/counter`, `server/modules/counter` and knex files for migrations and seed at `server/database`. After deleting any module application should be functional. This is true now for `post`, `counter`, `favicon` and `debug` modules, you can delete their dirs and app will still work and build.

For easier upgrading of starter kit in custom project, the `webpack.app_config.js` is added where app-specific webpack config should live, in this config one can add or override webpack rules used by the kit.

**Comment by mitjade** [comment]
@vlasenko This is awesome! Way more than I could have come up with my self.

It ads some additional complexity. That might cause some problems for someone just getting started, but all we need is to add some documentation explaining this and I do not see any problems here.

One small problem is that you get an error `Error: The migration directory is corrupt, the following files are missing: create_count.js, create_posts.js`, if you already have an existing `dev-db.sqlite3`. If you delete it it's OK. Do you think we would need to address this for existing useds?

**Comment by mitjade** [comment]
@vlasenko Since you already taken care of everything, I will try to write some docs on how to create a new module, or remove an existing one, when I have some more time. I have no other reservations regarding merging #118, except some code style changes I suggested.

**Comment by josephdburdick** [comment]
Great progress you guys. Looking forward to the next pull from upstream!

**Comment by vlasenko** [comment]
@mitjade Thanks Mitja! I am going to work on making this approach more simple/self-explaining today, while still keeping concept of `drop-in` modules.

**Comment by josephdburdick** [comment]
Will this eventually be merged into the `master` branch or is it considered "opt-in" and we should  start using this new branch for the "modular" version?

**Comment by vlasenko** [comment]
@josephdburdick It will be merged to `master` soon. We are still working on this stuff with Mitja @mitjade 
This is rather experimental stuff, but for sure I would like it to be battle-tested, just after we give it enough thought.

**Comment by vlasenko** [comment]
@mitjade Mitja, I have pushed another set of changes to https://github.com/sysgears/apollo-fullstack-starter-kit/tree/modularize branch to make the code more self-explanatory and IDE-friendly, please take a look. Please share your thoughts about what can be improved?

**Comment by vlasenko** [comment]
Resolved by commit:
https://github.com/sysgears/apollo-fullstack-starter-kit/commit/9bf0161e91bf999c072e64e4a9f9977bf454df9f
