### ISSUE TITLE
Semicolon consistency

### ISSUE THREAD

**Issue by josephdburdick** [sysgears/apollo-fullstack-starter-kit#115]
Hey guys, I hate to be that guy but can we get some consistency with semicolon use? In imports of files it looks like semicolons are skipped but everywhere else they are included. Is there a reason for this? Perhaps we could have some editor config included in the starter kit that enforces one or the other? Thanks in advance!

**Comment by vlasenko** [comment]
@josephdburdick I think enforcing semicolon consistency might be achieved with eslint rule. We have lint & test target run on every commit to this repo, so it will be enforced in the future.

**Comment by vlasenko** [comment]
@josephdburdick Okay, I am going to fix this in 15 mins
