### ISSUE TITLE
Add Material Design support

### ISSUE THREAD

**Issue by sakhmedbayev** [sysgears/apollo-fullstack-starter-kit#116]
It is not actually an issue rather a suggestion. It looks like [Material Design](https://material.io/) is great as well as this kit. Why not to support it?

**Comment by josephdburdick** [comment]
It's not that it's _not_ supported, it's just not already wired up. You can download this and replace 'reactstrap' (React-powered Bootstrap 4) with any front-end CSS framework you like.

**Comment by mairh** [comment]
Closing the issue due to inactivity and answer provided. Reopen in a case of any issue.

**Comment by mitjade** [comment]
This could now be achieved in the same way as done for `ui-bootstrap` or `ui-and` with #441 PR.
