### ISSUE TITLE
Persistent queries issue with GraphQLi error

### ISSUE THREAD

**Issue by swhamilton** [sysgears/apollo-fullstack-starter-kit#117]
The new code added in the persistent queries commit https://github.com/sysgears/apollo-fullstack-starter-kit/commit/de2fdec1e0182bb949ac89020c8d2f0298c72946 breaks GraphQLi.

`TypeError: req.body.map is not a function`

The following code in `src/server/api_server` assumes that all req.body are arrays.
```javascript
app.use(
    '/graphql',
    (req, resp, next) => {
        req.body = req.body.map(body => {
          return {
            query: invertedMap[ body.id ],
            ...body
          };
        });
      next();
    },
  );
```

I have not investigated what is involved with persistent queries so I cannot say this fix is correct, but this does protect the map from getting called on a non-array:

```javascript
import { invert, isArray } from 'lodash';
...
app.use(
    '/graphql',
    (req, resp, next) => {
      if (isArray(req.body)) {
        req.body = req.body.map(body => {
          return {
            query: invertedMap[ body.id ],
            ...body
          };
        });
      }
      next();
    },
  );
```

**Comment by vlasenko** [comment]
Thank you @swhamilton I have taken your patch and add some logic on top of it. We want to accept non persisted GraphQL queries only in DEV mode and only if they come from /graphiql URL. All the other unknown queries will be banned in persistGraphQL mode.

@mitjade Please take a look and share your concerns.

**Comment by vlasenko** [comment]
I think we should also remove `GraphiQL` link from UI in production mode, when persisted GraphQL queries are used.

**Comment by mitjade** [comment]
@vlasenko I think this ok. As long as you can still use GraphQL in dev mode this is fine with me.

**Comment by zirho** [comment]
@vlasenko Don't we want graphiql to work with queries in DEV mode?

**Comment by vlasenko** [comment]
@zirho Yes, graphiql queries should work in DEV mode. Don't they work for you now?

**Comment by zirho** [comment]
Nope not working. Fresh started. Go to graphiql by the button up right corner. Try to get post with Id.
