### ISSUE TITLE
batchInterval set to 500?

### ISSUE THREAD

**Issue by mitjade** [sysgears/apollo-fullstack-starter-kit#12]
I am interested why is batchInterval set to 500.

This causes my app to be really slow. If I set it to 20 everything is much faster. Just interested if this is there of a reason or can this be reduced?

**Comment by vlasenko** [comment]
I think, this question is not related to the starter kit, but rather to how Apollo Stack works and it should be asked here:
https://apollographql.slack.com/messages/react-apollo/
