### ISSUE TITLE
A question regarding to HMR

### ISSUE THREAD

**Issue by zirho** [sysgears/apollo-fullstack-starter-kit#125]
I turned the reactHotLoader ON and it seems everytime I change a literal in a UI component, it does a full-reloading. 
And I figured it's related to this line.
https://github.com/sysgears/apollo-fullstack-starter-kit/blob/master/src/client/index.jsx#L31

To prevent that, I need to turn `frontendRefreshOnBackendChange` flag off, which seems not right by the name of the flag.

I changed one of front end components, and it recognized it as a back-end change.
It may be related to SSR but I am not 100% sure.

Thanks!

**Comment by vlasenko** [comment]
@zirho When you change literal in UI component, do you see message like this in backend console?
`Force front-end current page refresh, due to change in backend at: ...`

**Comment by vlasenko** [comment]
@zirho Okay, I see some problem with this logic too, looking...

**Comment by vlasenko** [comment]
@zirho I have reworked front end reload on back end change logic. Should work as expected now

**Comment by zirho** [comment]
Cool thanks
