### ISSUE TITLE
build fails on Ubuntu

### ISSUE THREAD

**Issue by hhashmi** [sysgears/apollo-fullstack-starter-kit#131]
npm ERR! Linux 4.4.0-66-generic
npm ERR! argv "/root/.nvm/versions/node/v5.11.1/bin/node" "/root/.nvm/versions/node/v5.11.1/bin/npm" "run" "build"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! apollo-fullstack-starter-kit@1.0.0 build: `babel-node tools/webpack.run build`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the apollo-fullstack-starter-kit@1.0.0 build script 'babel-node tools/webpack.run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the apollo-fullstack-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/webpack.run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs apollo-fullstack-starter-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls apollo-fullstack-starter-kit
npm ERR! There is likely additional logging output above.

**Comment by vlasenko** [comment]
@hhashmi Seems you are using very outdated `node.js` version. Because this starter kit uses latest versions of all its dependencies, you should you latest `node.js` too.

**Comment by vlasenko** [comment]
@hhashmi I would recommend installing and updating node.js on your system via NVM:
https://github.com/creationix/nvm

**Comment by vlasenko** [comment]
@hhashmi I have tried to reproduce this bug on `Ubuntu 16.04` with stock `nodejs` `v4.2.6` and everything works for me. I don't see `Exit status 137` error.

**Comment by hhashmi** [comment]
Just found out that I'm on a VM and it was due to low amount of memory.
Increased memory of VM and it is working fine.

Thanx a lot for your inputs.
