### ISSUE TITLE
Problems while running on windows (Unknown signal: SIGUSR2)

### ISSUE THREAD

**Issue by GiladShoham** [sysgears/apollo-fullstack-starter-kit#14]
Hi,
I have a problem when running on windows, this code:
```js
if (__DEV__) {
      compiler.watch({}, reporter);

      compiler.plugin('done', () => {
        const { output } = serverConfig;
        startBackend = true;
        if (server) {
          server.kill('SIGUSR2');
        } else {
          runServer(path.join(output.path, output.filename));
        }
      });
    }
```
and specificlly this line:
```js
server.kill('SIGUSR2');
```
Are failing due to error:
Unknown signal: SIGUSR2

Have you tried to run it on windows? 
Do you have any idea how to solve this?

Thanks,
Gilad.

**Comment by vlasenko** [comment]
Yeah, it's weird. Webpack is using SIGUSR2 for hot code replacement on signal. SIGUSR2 seems to be not available on Windows.

The alternative is to comment out this line and change `webpack/hot/signal` entry point to `webpack/hot/poll?1000`. It should work on Windows.

**Comment by GiladShoham** [comment]
Thanks for the help,
I have also found out that change SIGUSR2 to SIGINT make it work.
(But I still have problems with the hot reload on windows)

**Comment by vlasenko** [comment]
If you are sending SIGINT, I believe the Node.js process will be simply terminated and according to the logic of `webpack.run.js` it will be restarted immediately after termination. Though this might work for you - it is not hot reload, it is just restart of backend process on source code modification.
