### ISSUE TITLE
How to update Application built on older version of starter kit to latest version 

### ISSUE THREAD

**Issue by hhashmi** [sysgears/apollo-fullstack-starter-kit#142]
I picked apollo-fullstack-starter-kit back in dec 2016 and started building my app on top of it.
I'm almost 80% done with and just now I noticed there are some changes in latest version of starter kit.

Now my question is how to I update my current application to latest version of starter kit.
FYI
I'm using mongo + mongoose + apollo - graphql subscription in my current application.

**Comment by vlasenko** [comment]
@hhashmi This is a good question.

Seamless upgrade process for this starter kit is planned to be implemented in the future, but we are not there yet.

If I were you I would checkout revision of apollo-fullstack-starter-kit that you have picked in dec 2016 and wrote the script to build diff between it and your app, to find out YOUR changes on top of original starter kit. Then I would checkout latest version of apollo-fullstack-starter-kit and applied this diff on top of it.

**Comment by hhashmi** [comment]
Looks like will have to do tons of work manually :)

ok what if I manage to transfer my application to current version so how, how soon that seamless upgrade process will be out?

Actually I'm concerned for future upgrade. For current version I'll manage it doing the dirty work but for future will defiantly need that

**Comment by vlasenko** [comment]
@hhashmi I cannot tell you when this will be implemented. We have worked only on one aspect of this task - making the examples for this starter kit modular:
https://github.com/sysgears/apollo-fullstack-starter-kit/pull/118
Many more aspects need to be handled to make upgrades seamless. It is a tough task and it is not clear yet who will work on it and when.
