### ISSUE TITLE
Async/await instead of Promises

### ISSUE THREAD

**Issue by vlasenko** [sysgears/apollo-fullstack-starter-kit#148]
Maybe it is worth looking into using async/await instead of Promises to make the code of this kit more expressive and elegant?

https://hackernoon.com/6-reasons-why-javascripts-async-await-blows-promises-away-tutorial-c7ec10518dd9

**Comment by mitjade** [comment]
I'm all for it!
My only concern would be, if someone can't update to node 7.6 or above, since this feature is only available there.

**Comment by mitjade** [comment]
Writing Promises to seed more complicated database related tables is a nightmare. This would really simplify something like that.

**Comment by vlasenko** [comment]
@mitjade Here is the thing. We are using Webpack for Backend and Frontend, and hence all the starter kit code is transformed by Babel, so everything will work with previous Node versions!

Well, knexfile.js and Knex migrations currently are not Babelified, but we can easily Babelify them:
https://github.com/sysgears/apollo-fullstack-starter-kit/blob/a196852d435f19ca2adaf02a0264e2c4ed2e7f9c/knexfile.js#L1-L4

**Comment by mitjade** [comment]
Then I would for sure like to see this added.

If you are willing to give this a go, I can help out by doing this for post example code.

**Comment by vlasenko** [comment]
Yeah, I think we should upgrade to async/await, this will make the code more readable. 

At the moment I'm still busy with writing integration tests for Posts and Comments, when I will finish them, I' will take a look. If you will have time earlier feel free to upgrade some parts of the code to async/await

**Comment by mitjade** [comment]
OK. Will let you know if I start.

**Comment by mitjade** [comment]
This really looks great! I love how this cleans up the code.

**Comment by vlasenko** [comment]
@mitjade Yeah, the readability of simple code is better. The readability of complex code is worser :)
