### ISSUE TITLE
Turn off SSR

### ISSUE THREAD

**Issue by GiladShoham** [sysgears/apollo-fullstack-starter-kit#15]
Hi,
I really like your starter kit and I'm using it for my apps.
But recently I understand that most of the time I don't really need SSR.
([See reference here](http://jamesknelson.com/universal-react-youre-doing-it-wrong/))
It is work out of the box using the starter kit, but it require more maintenance, and it's time-consuming. (for example, authentication mechanism with SSR are much harder)
Also, for example, using a library such as highchairs which need the window, and require a lot of effort to somehow support SSR.

I'm wondering is there a way to turn off / comment everything related to SSR?

Thanks a lot!
Gilad.

**Comment by vlasenko** [comment]
Per your request, I've added configurable SSR support:
https://github.com/sysgears/apollo-fullstack-starter-kit/commit/b60c7e633ee7be88df12fa3fc112370f931b6ad4

To turn off SSR please set `package.json` `ssr` field to `false`

**Comment by GiladShoham** [comment]
That's awesome!
Thanks!
