### ISSUE TITLE
Limit on modules at client side??

### ISSUE THREAD

**Issue by hhashmi** [sysgears/apollo-fullstack-starter-kit#151]
I'm converting my application manually, built in older version of starter kit to newer version 
https://github.com/sysgears/apollo-fullstack-starter-kit/issues/142

I'm facing a weird issue ,
src/client/modules/index.jsx
I have converted my 5 modules to newer version but at one time it is not letting me use all of these modules. In total it is not letting me use more than 7 modules at a time. As soon as I add 8th module I get following err

> webpack-for-frontend bundle is now INVALID.
> /Users/Hassan/MyProject/001_apollo/node_modules/lodash/lodash.js:6055
>       return arrayFilter(nativeGetSymbols(object), function(symbol) {
>                          ^
> 
> RangeError: Maximum call stack size exceeded
>     at getOwnPropertySymbols (native)
>     at getSymbols (/Users/Hassan/MyProject/001_apollo/node_modules/lodash/lodash.js:6055:26)
>     at baseGetAllKeys (/Users/Hassan/MyProject/001_apollo/node_modules/lodash/lodash.js:3064:59)
>     at getAllKeys (/Users/Hassan/MyProject/001_apollo/node_modules/lodash/lodash.js:5891:14)
>     at baseClone (/Users/Hassan/MyProject/001_apollo/node_modules/lodash/lodash.js:2695:39)
>     at /Users/Hassan/MyProject/001_apollo/node_modules/lodash/lodash.js:2702:34
>     at arrayEach (/Users/Hassan/MyProject/001_apollo/node_modules/lodash/lodash.js:537:11)
>     at baseClone (/Users/Hassan/MyProject/001_apollo/node_modules/lodash/lodash.js:2696:7)
>     at /Users/Hassan/MyProject/001_apollo/node_modules/lodash/lodash.js:2702:34
>     at arrayEach (/Users/Hassan/MyProject/001_apollo/node_modules/lodash/lodash.js:537:11)
> 

Following is my index.jsx file

```
import './counter';
import './favicon';
import './post';

import './myModule1';
import './myModule2';
import './myModule3';
import './myModule4';
import './myModule5';

export * from './connector';
```

What I'm doing right now is just comment any one of this and then continue working on next module. 
Anyone knows what the issue is and how to fix it.

**Comment by vlasenko** [comment]
@hhashmi Weird, yeah, I see this problem too when I copied `post` module several times and included all these copies. Looks like some problem with lodash consuming too much stack for one of its recursive methods. We need to find what is exactly triggering it inside starter kit and figure out workaround that doesn't result in stack consumption growth

**Comment by vlasenko** [comment]
@hhashmi Seems the problem is inside Persistent GraphQL queries support. If you set `persistGraphQL` to `false` in `package.json` this problem will gone. I will look into this at the beginning of next week. I recommend you to turn off persistGraphQL for now as a work around

**Comment by hhashmi** [comment]
@vlasenko thanx it works.

**Comment by vlasenko** [comment]
This issue is linked with this one: https://github.com/sysgears/persistgraphql-webpack-plugin/issues/3

I'm still trying to find where the problem is. Looks like the problem is that query documents parsed via `graphql` are not `cloneDeep` friendly, but I'm not 100% sure yet. Going to look more into this tomorrow

**Comment by vlasenko** [comment]
`persistgraphql-webpack-plugin` now has workaround for this problem, since version `0.2.2`
