### ISSUE TITLE
TypeError: __webpack_require__.i(...) is not a function

### ISSUE THREAD

**Issue by hhashmi** [sysgears/apollo-fullstack-starter-kit#161]
#142 when I try to use moment() in any react component, I get TypeError: __webpack_require__.i(...) is not a function

> 
> TypeError: __webpack_require__.i(...) is not a function
>     at new CallMonitor (/Users/Hassan/myProject/001/build/server/index.js:2891:88)
>     at walkTree (/Users/Hassan/myProject/001/node_modules/react-apollo/src/server.ts:43:24)
>     at walkTree (/Users/Hassan/myProject/001/node_modules/react-apollo/src/server.ts:80:7)
>     at walkTree (/Users/Hassan/myProject/001/node_modules/react-apollo/src/server.ts:80:7)
>     at walkTree (/Users/Hassan/myProject/001/node_modules/react-apollo/src/server.ts:80:7)
>     at /Users/Hassan/myProject/001/node_modules/react-apollo/src/server.ts:90:11
>     at forEachSingleChild (/Users/Hassan/myProject/001/node_modules/react/lib/ReactChildren.js:51:8)
>     at traverseAllChildrenImpl (/Users/Hassan/myProject/001/node_modules/react/lib/traverseAllChildren.js:77:5)
>     at traverseAllChildren (/Users/Hassan/myProject/001/node_modules/react/lib/traverseAllChildren.js:172:10)
>     at Object.forEachChildren [as forEach] (/Users/Hassan/myProject/001/node_modules/react/lib/ReactChildren.js:71:3)
>     at walkTree (/Users/Hassan/myProject/001/node_modules/react-apollo/src/server.ts:88:16)
>     at walkTree (/Users/Hassan/myProject/001/node_modules/react-apollo/src/server.ts:80:7)
>     at /Users/Hassan/myProject/001/node_modules/react-apollo/src/server.ts:90:11
>     at forEachSingleChild (/Users/Hassan/myProject/001/node_modules/react/lib/ReactChildren.js:51:8)
>     at traverseAllChildrenImpl (/Users/Hassan/myProject/001/node_modules/react/lib/traverseAllChildren.js:77:5)
>     at traverseAllChildrenImpl (/Users/Hassan/myProject/001/node_modules/react/lib/traverseAllChildren.js:93:23)
>     at traverseAllChildren (/Users/Hassan/myProject/001/node_modules/react/lib/traverseAllChildren.js:172:10)
>     at Object.forEachChildren [as forEach] (/Users/Hassan/myProject/001/node_modules/react/lib/ReactChildren.js:71:3)
>     at walkTree (/Users/Hassan/myProject/001/node_modules/react-apollo/src/server.ts:88:16)
>     at walkTree (/Users/Hassan/myProject/001/node_modules/react-apollo/src/server.ts:80:7)
>     at walkTree (/Users/Hassan/myProject/001/node_modules/react-apollo/src/server.ts:80:7)
>     at walkTree (/Users/Hassan/myProject/001/node_modules/react-apollo/src/server.ts:80:7)

**Comment by vlasenko** [comment]
@hhashmi I would like to close this issue, because it is clearly not a problem of this starter kit.

**Comment by hhashmi** [comment]
Yes you are correct it is not related to starter kit. 
It was a moment related issue.

Just in case if anyone else gets same issue.

https://github.com/moment/moment/issues/2608
