### ISSUE TITLE
Updating record restoring last values  

### ISSUE THREAD

**Issue by hhashmi** [sysgears/apollo-fullstack-starter-kit#169]
Most of the times after updating record I get last values in list and even some times on update screens.
I have to refresh my browser to get updated values.

How to fix it?

**Comment by vlasenko** [comment]
Please be more specific about your problem. What problem do you have exactly and what are the reproduction steps?

**Comment by vlasenko** [comment]
@hhashmi If you mean posts and comments problem in the newest version of the kit, then it should be fixed via commit: https://github.com/sysgears/apollo-fullstack-starter-kit/commit/854f30d91c56734aae02a977c14ca8a47a7d2e0e

E.g. please check the latest version of the kit.

**Comment by hhashmi** [comment]
ok here is a scenario
I have 3 records in list


1 - Employee 1
2 - Employee 2
3 - Employee 3

Now I click on edit link for 2nd record (Employee 2) and change it to (Employee 2nd) click on Submit. It come back to the list with updated values

Now here comes the problem
6 out of 10 time I have refresh my browser to see updated list while values are update in db.
This is not happening all the times but mostly.

**Comment by vlasenko** [comment]
@hhashmi Closing as inappropriate. We do not provide support for your project, only for this starter kit.
