### ISSUE TITLE
Integrate with apollo-passport

### ISSUE THREAD

**Issue by GiladShoham** [sysgears/apollo-fullstack-starter-kit#17]
Hi,
I'm trying to integrate [apollo-passport](https://github.com/apollo-passport/apollo-passport).

Part of the client confuguration is to add using the local startegy as described here:
```js
// Configure Apollo
import ApolloClient, { createNetworkInterface } from 'apollo-client';
import ApolloPassport from 'apollo-passport/lib/client';
import ApolloPassportLocal from 'apollo-passport-local/lib/client';
import apMiddleware from 'apollo-passport/lib/client/middleware';

const networkInterface = createNetworkInterface('/graphql');
networkInterface.use([ apMiddleware ]);

const apolloClient = new ApolloClient({ networkInterface });
const apolloPassport = new ApolloPassport({ apolloClient });

apolloPassport.use('local', ApolloPassportLocal);
```

Of course on the server side this won't really work because of localstorage doesn't exist on the server side.

There is an issue about it over there [Isomorphic app](https://github.com/apollo-passport/apollo-passport/issues/10) which points to this example:

```js
if (__CLIENT__) {
  const networkInterface = createNetworkInterface('/graphql');
  networkInterface.use([ apMiddleware ]);

  apolloClient = new ApolloClient({ networkInterface });
  apolloPassport = new ApolloPassport({ apolloClient });
  apolloPassport.use('local', ApolloPassportLocal);
}
```

Therefor i added on apollo_client file something like:
const createApolloPassport = apolloClient => {
```js
const createApolloPassport = apolloClient => {
  if (__CLIENT__) {
    apolloClient = apolloClient || defaultApolloClient;
    let apolloPassport = new ApolloPassport({ apolloClient });
    apolloPassport.use('local', ApolloPassportLocal);
    return apolloPassport;
  }
  return;
};
```

But the __CLIENT__ is always false.
I'm wondering when will this be a true value?
I thought that disable the SSR will solve the problem, but it doesn't.

Help would be welcomed.
Thanks a lot.
Gilad.

**Comment by vlasenko** [comment]
`__CLIENT__` is obviously always false on the server side, hence if you `console.log` its value, you will always see `false` in the server logs. `__CLIENT__` is obviously always true on the client side, hence if you `console.log` its value, you will always see `true` in the web browser console.

I'm closing this one because it doesn't really look as an issue of this starter kit, it rather looks as a support request. Please rework this issue to point out the concrete problem in this Starter Kit.
