### ISSUE TITLE
Is there any reason why this kit is not using gql template tag

### ISSUE THREAD

**Issue by mairh** [sysgears/apollo-fullstack-starter-kit#173]
I was wondering if there is any specific reason why this kit is not using `ggl` tag from `react-apollo`. Their docs seem to promote using the template tag.

[API DOC](http://dev.apollodata.com/react/api.html)

**Comment by vlasenko** [comment]
@mairh This kit doesn't stop you using `gql` tag in any way. Please try first before opening issues.

**Comment by mitjade** [comment]
Take a look at https://dev-blog.apollodata.com/webpacking-your-graphql-documents-bf9697ed259b

**Comment by mairh** [comment]
Thanks. Exactly what I needed to understand this
