### ISSUE TITLE
Cannot run project on Ubuntu bash on Windows

### ISSUE THREAD

**Issue by josephdburdick** [sysgears/apollo-fullstack-starter-kit#174]
Related to https://github.com/sysgears/apollo-fullstack-starter-kit/issues/89 and a recent commit (https://github.com/sysgears/apollo-fullstack-starter-kit/commit/9db68821d3b6c4e10dc3d3851b7f1829f517cafd) it appears that a dependency of the package `wait-for-port` is not allowing the project to run. Error info found [here](https://github.com/sysgears/apollo-fullstack-starter-kit/commit/9db68821d3b6c4e10dc3d3851b7f1829f517cafd#commitcomment-22056941).

**Comment by vlasenko** [comment]
Hopefully https://github.com/sysgears/apollo-fullstack-starter-kit/commit/bcd282fec6fc455b1e09568f15deb36b08e60558 will fix this problem. But I'm not sure, we need to check

**Comment by josephdburdick** [comment]
I'll check and report back.

**Comment by josephdburdick** [comment]
This problem is now resolved.

**Comment by vlasenko** [comment]
@josephdburdick Cool. Thank you so much Joe, for testing this!
