### ISSUE TITLE
Roadmap tracker?

### ISSUE THREAD

**Issue by mairh** [sysgears/apollo-fullstack-starter-kit#175]
Hi, Do you have any place where you have documented the roadmap for this kit? For e.g we could do something like this https://github.com/reactql/cli/issues/10 and track the upcoming features. It would make it easy for the contributors to work on this kit too.

**Comment by vlasenko** [comment]
Hi @mairh Great idea! I've added issue for Roadmap, feel free to post ideas there:
https://github.com/sysgears/apollo-fullstack-starter-kit/issues/176
