### ISSUE TITLE
Failed to load resources 

### ISSUE THREAD

**Issue by mairh** [sysgears/apollo-fullstack-starter-kit#177]
It seems like the kit can not find bundled resource anymore and thus the user can not take any actions.

I did a fresh clone about 30 mins ago and ran the following commands as specified in the README

`yarn`
`yarn seed`
`yarn watch`

<img width="1680" alt="screen shot 2017-05-10 at 11 42 08" src="https://cloud.githubusercontent.com/assets/4072250/25890482/4724f37a-3576-11e7-9d0c-39a849728981.png">

Would you like me to send any additional information?

**Comment by vlasenko** [comment]
@mairh Looks like you are not following instructions. In dev mode you should open `http://localhost:3000` which hosts webpack-dev-server and frontend not `http://localhost:8080`. The resources in dev mode are hosted from `http://localhost:3000` to let Webpack HMR for front-end do its job. It is still helpful in some situations to check what `http://localhost:8080` and hence the backend generates, but it is expected that resources will be not present on `8080`, but are at `3000` instead, in dev mode

**Comment by vlasenko** [comment]
I understand that this is confusing, but thats how webpack default infrastructure works. We have already tweaked this infrastructure in different ways. So maybe it would be worth to chop out `webpack-dev-server` and try to use `webpack-hot-middleware` instead to get rid of this confusion. But it is not all roses too, it will have its own drawbacks

**Comment by mairh** [comment]
Thanks for pointing out my mistake. It was a mind f**k

**Comment by vlasenko** [comment]
This is mind blowing thing, indeed :)

**Comment by vlasenko** [comment]
Actually thanks for reminding me about this crap :) I'm going to take another look during next few days to get rid of it by utilizing:
https://github.com/webpack/webpack-dev-middleware

**Comment by vlasenko** [comment]
This has drawback though that you need to pull in webpack config into application code, which is crappy solution too ...

**Comment by vlasenko** [comment]
I feel like ideal solution to this problem need to be invented, it doesn't exist yet
