### ISSUE TITLE
Is GraphQL subscription only used in counter example?

### ISSUE THREAD

**Issue by mairh** [sysgears/apollo-fullstack-starter-kit#179]
I noticed that you have written subscription code for Post example too. I wonder what piece is missing to see it in effect?

**Comment by mitjade** [comment]
@mairh What exactly seems to be the problem? I tested it and it seems to work.

**Comment by mairh** [comment]
well, only the counter is being updated on a different browser. No effect in the case of post or comment subscription. I will try to install a new clone of this project and check again.

**Comment by vlasenko** [comment]
@mairh @mitjade Sorry guys, it was me, I have pushed the fix

**Comment by mairh** [comment]
ah great. Just noticed you pushed a fix.
