### ISSUE TITLE
React Storybook

### ISSUE THREAD

**Issue by bagshik** [sysgears/apollo-fullstack-starter-kit#184]
First of all, thanks for this awesome starter-kit. I think adding [React Storybook](https://github.com/storybooks/storybook) to the starter-kit would enhance and improve the overall developer experience by having visual TDD next to traditional TDD. They also have some great addons to write tests and document components next to their stories :

- [addon-info](https://github.com/storybooks/storybook/blob/master/packages/addon-info) - Annotate stories with extra component usage information
- [storybook-addon-specifications](https://github.com/mthuret/storybook-addon-specifications) - Write tests next to your stories and display their results

What are your thoughts about this? I would gladly help if you can point me in the right direction to make it work with the current Webpack configuration 👍

**Comment by vlasenko** [comment]
@bagshik What kind of integration do you expect to have with this starter kit? From what I see they are completely orthogonal. You can install storybook into the project based on this starter kit by following `storybook` installation instructions and it should work out of the box.You will be able to use storybook for your presentational React components just fine. If you would like to use React Storybook for React container GraphQL components then it will require more work from you to set things up, your best bet would be probably to mock out the backend: 
http://dev.apollodata.com/tools/graphql-tools/mocking.html

We are doing backend mocking already in integration tests, so you might find inspiration there:
https://github.com/sysgears/apollo-fullstack-starter-kit/blob/master/src/client/modules/counter/containers/counter_int.spec.js
https://github.com/sysgears/apollo-fullstack-starter-kit/blob/master/src/client/modules/post/containers/post_int.spec.js
https://github.com/sysgears/apollo-fullstack-starter-kit/blob/master/src/client/test-helpers/apollo_renderer.js

**Comment by bagshik** [comment]
@vlasenko Thanks for your answer, I will look into that. Like you said, Storybook worked out of the box with Presentational components. I wanted to see if there was a way to extend the Webpack configuration to make it work with Container components. I tried multiple setups with loaders, decorators, etc. but I always ran into some kind of issue. I agree with what you said though, I will try to make it work by mocking the backend 👍

**Comment by vlasenko** [comment]
@bagshik `spinjs` supports Storybook now, check this code to integrate it:
https://github.com/sysgears/spinjs/blob/master/docs/programmatic.md
It will let storybook to utilize the same Webpack config used by the kit. So you will be able to import container components in storybook stories. You will still need to mock backend, but you can check how we do it in the tests, that mocking code should work for storybook stories too.
