### ISSUE TITLE
Ws subscriptions on heroku

### ISSUE THREAD

**Issue by gilesbradshaw** [sysgears/apollo-fullstack-starter-kit#19]
Can you give me a pointer re getting websockets to work on heroku?

**Comment by vlasenko** [comment]
@gilesbradshaw It works out of the box. Open https://apollo-fullstack-starter-kit.herokuapp.com in the two web browser tabs, increment counter in one tab and check another tab - it will increment too, thanks to subscription.

**Comment by gilesbradshaw** [comment]
It doesn't for me by going to those urls ...  Maybe something wrong my end?  I've been playing with this with my app from what I understand heroku only gives you one port in process.env.PORT

**Comment by vlasenko** [comment]
WS is served on the same port. It works for me both on that Heroku URL and locally, inside the Chrome browser

**Comment by vlasenko** [comment]
Subscriptions on https://apollo-fullstack-starter-kit.herokuapp.com/ works for me in Firefox too.

**Comment by gilesbradshaw** [comment]
Hi That's odd.  I can't get it to work in anything.  I shall try tonight from a different network.

**Comment by gilesbradshaw** [comment]
ok it works now I am at home must have been to do wth network thanks for your time!
