### ISSUE TITLE
Google universal analytics as part of the starter kit

### ISSUE THREAD

**Issue by mairh** [sysgears/apollo-fullstack-starter-kit#196]
How do you think if we support Google Universal analytics out of the box? I can create a PR if you think we would like to have it in the kit.

Usually, at some point in time, people would like to integrate GA in their app, but I am not sure if we leave it up to them to tackle or provide the feature in this kit.

**Comment by vlasenko** [comment]
Yes, sure, sounds good. Lets integrate it

**Comment by mairh** [comment]
I'll create a PR in a day or two. Closing the issue now (since technically this is not an issue)
