### ISSUE TITLE
Error running the kit after the latest update

### ISSUE THREAD

**Issue by mairh** [sysgears/apollo-fullstack-starter-kit#199]
Getting the following error after the commit https://github.com/sysgears/apollo-fullstack-starter-kit/commit/2ad36e9ce54279cd343a97242351d9fb7c9b334a was merged to master.

`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Schema must be an instance of GraphQLSchema. Also, ensure that there are not multiple versions of GraphQL installed in your node_modules directory`

Steps to reproduce:

1) Fetch the latest code
2) yarn
3) yarn watch
4) Go to http://localhost:3000/

**Comment by vlasenko** [comment]
Oh, okay, I'm going to look now, thanks for reporting!

**Comment by vlasenko** [comment]
Should be fixed via: https://github.com/sysgears/apollo-fullstack-starter-kit/commit/a5c54b1621b5f0ac95ccbf96116a2b3ed8e4bcfe
