### ISSUE TITLE
How to add post using graphiql?

### ISSUE THREAD

**Issue by sakhmedbayev** [sysgears/apollo-fullstack-starter-kit#200]
Sorry guys for asking these kind of questions here, but I have hard time to figure out how to add a post using graphiql. Can you please help? I understand I need to issue this query, what goes as `postInfo`?

    mutation addPost($input: AddVideoInput!) {
        addVideo(input: $input) {
            ... postInfo
        }
    }

**Comment by mairh** [comment]
'postInfo' is a fragment applied to 'addPost' mutation using spread operator.

I am not sure how does your 'Post' type looks like but in graphiql you can use fragment to pass the 'postInfo'

Something like

'''
fragment postInfo on Post {
  id 
  content
}
'''

**Comment by vlasenko** [comment]
To add post using GraphiQL you should use the following mutation request:
```
mutation addPost($input: AddPostInput!) {
    addPost(input: $input) {
    	id
    	title
    	content
  	}
}
```

In "query variables" tab:
```
{
  "input": {
    "title": "Some post title",
    "content": "Some post content"
  }
}
```

Expected output:
```
{
  "data": {
    "addPost": {
      "id": "22",
      "title": "Some post title",
      "content": "Some post content"
    }
  }
}
```

**Comment by sakhmedbayev** [comment]
Thank you!
