### ISSUE TITLE
Heroku deploys no longer work

### ISSUE THREAD

**Issue by j-jackson** [sysgears/apollo-fullstack-starter-kit#210]
I noticed that the heroku [demo](https://apollo-fullstack-starter-kit.herokuapp.com/) in the readme no longer works so I tried to [deploy a new version](https://gql-apollo-demo.herokuapp.com/) using a new clone from master but It still doesn't work. (see below)

![screenshot 2017-05-31 13 14 49](https://cloud.githubusercontent.com/assets/22781082/26614551/85c727b2-4604-11e7-8b8d-3368082f17ad.png)

**Comment by j-jackson** [comment]
Actually, it looks like running in production mode locally throws the same error.

**Comment by vlasenko** [comment]
@j-jackson Thanks for reporting! Looking...

**Comment by j-jackson** [comment]
Thanks @vlasenko, production build works now! 

Did you tested it in dev mode? Im seeing the same error with `yarn watch`

**Comment by j-jackson** [comment]
sorry, ignore my last comment.
