### ISSUE TITLE
Invalid prop `aphroditeCss`

### ISSUE THREAD

**Issue by mitjade** [sysgears/apollo-fullstack-starter-kit#22]
When I `npm start` app I get a warning:

`Warning: Failed prop type: Invalid prop 'aphroditeCss' of type 'string' supplied to 'Html', expected 'object'.`

If I replace `aphroditeCss={css.content}` with `aphroditeCss={css}` in `src/server/middleware/website.jsx`, the warning is gone. Is this a bug or am I doing something wrong?

**Comment by vlasenko** [comment]
@mitjade You have outdated `ui/components/html.jsx`, please check

**Comment by mitjade** [comment]
You are right. Thank you for pointing it out.
