### ISSUE TITLE
Webpack’ing your GraphQL Documents

### ISSUE THREAD

**Issue by mitjade** [sysgears/apollo-fullstack-starter-kit#23]
Was reading https://dev-blog.apollodata.com/webpacking-your-graphql-documents-bf9697ed259b#.vd08fntp4 and tried this out on my fork.

Would this be something you might be interested in for this starter kit?

https://github.com/mitjade/apollo-fullstack-starter-kit/commit/56fdcbe192a46d12b38404e766bd17bfe3b212b4

Any thoughts, suggestions...

Can create a PR when I also add persisted queries.

**Comment by vlasenko** [comment]
Yes, please proceed with preparing PR

**Comment by vlasenko** [comment]
Thanks

**Comment by vlasenko** [comment]
I would have left some example of `gql` query too along with `.graphql` files, lifting everything to `.graphql` files might not be convenient.

**Comment by mitjade** [comment]
https://github.com/sysgears/apollo-fullstack-starter-kit/pull/24
