### ISSUE TITLE
favicon support

### ISSUE THREAD

**Issue by GiladShoham** [sysgears/apollo-fullstack-starter-kit#28]
Hi,
It will be great to add favicon support.
This requires few steps/options:
1. Add ico type to the loader of jpg/jpeg/png/svg
2. make sure the ico is available from the root app somehow - myhost/favicon.ico
3. Maybe add [favicons-webpack-plugin](https://github.com/jantimon/favicons-webpack-plugin) to generate all the different icons (for browser, iphone, windows tiles and so on)
4. change the html.jsx or maybe use [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) to generate the necessary code.
it can also be generated once using [realfavicongenerator](https://realfavicongenerator.net) and insert it hardcoded to the html.jsx
should look something like
```html
<link rel="apple-touch-icon" sizes="180x180" href={require('../../img/logos/favicons/apple-touch-icon.png')}/>
<link rel="icon" type="image/png" href={require('../../img/logos/favicons/favicon-32x32.png')} sizes="32x32"/>
<link rel="icon" type="image/png" href={require('../../img/logos/favicons/favicon-16x16.png')} sizes="16x16"/>
<link rel="manifest" href="/manifest.json"/>
<link rel="mask-icon" href={require('../../img/logos/favicons/safari-pinned-tab.svg')} color="#5bbad5"/>
<meta name="theme-color" content="#ffffff" />
```
(Also need to think about the manifest.json)

What do you think?

**Comment by GiladShoham** [comment]
One more:
Using this code hardcoded in index.jsx it works on dev correctly.
But after compile when running in prod env, it looks like it look for the favicons pngs in the wrong folder ie: 
```
href="/./assets/6f9927a38c643c8f5fcac15a6c15aa04.png
```
instead of:
```
href="/assets/./assets/6f9927a38c643c8f5fcac15a6c15aa04.png
```
(it should be with assets twice i think).
It only happen for the favicons, for other images it works correctly.

(i remember something similar before a month when running on dev which looks like it search something in the prod url)
Any idea?

**Comment by vlasenko** [comment]
Hi @GiladShoham 

Yes, properly supporting favicon's would be nice I think.

**Comment by GiladShoham** [comment]
I continue investigating the problem with my favicon and found:

1. in the [index.jsx](https://github.com/sysgears/apollo-fullstack-starter-kit/blob/5a54c532f91500ff5c083682c3180f46e4030fa5/src/ui/components/html.jsx#L10) there is check if it's dev or not, if not it will add /assets and find the correct url with the assetMap
2. most of the images like the logo is found both under build/server/assets and build/client/assets and therefor found in the assets.json.
3. the favicon is found only on build/server/assets so it's not in the assetMap. so i can't use this same technics.

I consider adding ManifestPlugin to server plugins to create another assetMap but it looks very wrong for me, and it's kind of workaround instead take care the real problem.

Is there any reason why other pngs are both in client and server and those favicon not? 
Does adding assetMap for the server assets is reasonable solution?

Thanks.

**Comment by vlasenko** [comment]
@GiladShoham 
> Is there any reason why other pngs are both in client and server and those favicon not?

I'm not sure what you are talking about, when I run 'npm run build' all the images are placed into `build/client/assets`

**Comment by vlasenko** [comment]
@GiladShoham Ah, I understand you now. You are talking about image files that are placed into `build/server`, during development phase, I will look into this, whether it is still needed...

**Comment by vlasenko** [comment]
@GiladShoham I think all your concerns raised in this ticket should be resolved by commit:
https://github.com/sysgears/apollo-fullstack-starter-kit/commit/1f84c6b4bc1219bf62a21d9cd9bf679f69e81dcf

**Comment by GiladShoham** [comment]
@vlasenko 
Thank you.
It's still needed.
Meantime i did some workaround. 
I create new loader for the favicon files, without hashing in the name.
Then i faced another problem (when put it in the head on html.jsx) it didn't sent to the client.
So i required them as well in the body in hidden div (which is really bad solution), so when reference them in the link href in the head i found them.

By the way, here is a [great article about favicons and web pack](https://medium.com/tech-angels-publications/bundle-your-favicons-with-webpack-b69d834b2f53#.v3cgrsldk).

(it didn't worked very well for me exactly like this, it did create the files in the output, but still didn't sent to the client without the workaround).
And later i decided to move it to dedicated loader in the config.

**Comment by vlasenko** [comment]
@GiladShoham 
Yes, I'm aware, that this can be tricky. I believe I have implemented it the proper way in the commit:
https://github.com/sysgears/apollo-fullstack-starter-kit/commit/1f84c6b4bc1219bf62a21d9cd9bf679f69e81dcf

As in that article I use require.context as well to require all the favicon images and favicon metadata from `src/assets` folder as specified in the link you have posted (by the way you can put other images into this folder and they will appear in assetMap with hash from their contents in the name). But above that I also use hashing on favicon files as I do for all the other image assets, so long term caching is done better then described in the link you posted - e.g. when underlying icon contents change - the name will also change, because hash from file contents changes.

**Comment by GiladShoham** [comment]
Looks great!
I'll check it soon.
I think it will be better to copy the favicon.ico to the root as well (without hashing) because some browsers are looking for this exact file in the root by default.

**Comment by vlasenko** [comment]
@GiladShoham Yes, I think you are right. I have moved all assets into root URL and added exception for favicon.ico to not have hash in its name, please see commit:
https://github.com/sysgears/apollo-fullstack-starter-kit/commit/9c3ed91c566484989c6ab062d5de96b5c7bfda2b

**Comment by GiladShoham** [comment]
@vlasenko 
Thanks!
I'll merge it to my project in few days.
