### ISSUE TITLE
Question: Does component Main need prop named router?

### ISSUE THREAD

**Issue by lionkeng** [sysgears/apollo-fullstack-starter-kit#3]
Hi!
I am looking at the code for the client-side. Does the Main component need a prop named `router`? How is it used? See lines 14 and 27 in `src/client/index.jsx`

**Comment by vlasenko** [comment]
Hi!
No. Thanks for noticing! Fix has been pushed:
https://github.com/sysgears/apollo-fullstack-starter-kit/commit/20afa3dfe31368c1f2fa90c95e9dc8479f3fbbbf
