### ISSUE TITLE
Migrate to Webpack 2

### ISSUE THREAD

**Issue by Jose4gg** [sysgears/apollo-fullstack-starter-kit#30]
Please do an update to webpack 2.

**Comment by vlasenko** [comment]
Why to do an update to Webpack 2? Tree shaking is still done better with Webpack 1, so I don't see reasons to update to Webpack 2 at the moment.

**Comment by vlasenko** [comment]
We will migrate to Webpack 2, when this issue will be resolved:
https://github.com/webpack/webpack/issues/2867

Hopefully this will happen very soon.

**Comment by vlasenko** [comment]
I think we can migrate to Webpack 2 if we will utilize this plugin:
https://www.npmjs.com/package/babel-plugin-transform-imports

This should fix tree-shaking issues in Webpack 2 for ES6 modules

**Comment by vlasenko** [comment]
Followup. Looks like Webpack 2 is still considerably worser then Webpack 1 for Tree Shaking:
https://github.com/webpack/webpack/issues/2867#issuecomment-285818931

Hence, I would like postpone migration to Webpack 2 until it start to perform the same or better then Webpack 1 for Tree Shaking.

**Comment by yishaic** [comment]
Hi @vlasenko 
4 days ago you wrote 

> I would like to postpone migration to Webpack 2 until it start to perform the same or better then Webpack 1 for Tree Shaking

And also https://github.com/webpack/webpack/issues/2867 is still open.
What have changed? I'm curious :)

**Comment by vlasenko** [comment]
@yishaic Webpack 1 has been marked as deprecated:
http://webpack.github.io/docs/

Though tree shaking is still working better in Webpack 1, lacking of interest of the Webpack developers to support Webpack 1 leaves us as having no choice but migrate to Webpack 2 and hope that Tree Shaking issues will be solved soon somehow
