### ISSUE TITLE
Merge SCSS files before injecting into HTML

### ISSUE THREAD

**Issue by josephdburdick** [sysgears/apollo-fullstack-starter-kit#34]
Hi guys, it's me again :metal:. I noticed that Bootstrap SCSS and `styles.scss` are both included inside `html.jsx`. There's a few things here and I just wanted some clarification.
```
<style dangerouslySetInnerHTML={{ __html:
          require('../styles.scss')._getCss() +
          require('../bootstrap.scss')._getCss()
}}/>
```

1. The first thing that pops out to me is that `styles.scss` is loaded before bootstrap. I understand you might want to assign variables in `styles.scss` that `bootstrap.scss` would then use in place of their own, but any other css would likely be overridden by Bootstrap and that may be undesired for some developers.
2. You could leverage Sass imports and include `bootstrap.scss` internally at the top of the `styles.scss` file. If you're setting `styles.scss` to be before `bootstrap.scss` because you want to assign variables, a `_variables.scss` can be created. Note the underscore there, it allows variables to be scoped into the .scss file that imported it. Place bootstrap variable overrides in that and include as follows:

```
// styles.css
@import 'variables';
@import 'functions';
@import 'mixins';
@import 'bootstrap';

body {
  background: $gray-lightest;
}
```
Now my directory structure looks like this: (note: I added a styles directory because I plan on having quite a few modular files for Sass support)
```
style
├── _functions.scss
├── _mixins.scss
├── _variables.scss
├── bootstrap.scss
└── styles.scss
```
And now my `html.jsx` has the following: 
```
<style dangerouslySetInnerHTML={{ __html:
          require('../styles.scss')._getCss()
}}/>
```
No rush on replying but I am curious about this. Thanks guys!

**Comment by vlasenko** [comment]
Hi Joe,

Yes, I think the order need to be changed vice versa, e.g. bootstrap.scss need to be loaded first, and styles.scss second.

The reason for separation is to speed up hot code reload for styles. Bootstrap styles are pretty big and we wanted to separate them out, so that they don't slow down reloading of custom styles.

**Comment by josephdburdick** [comment]
Just following up here, it looks like splitting up the files like they are now increases build speed but one of the largest benefits of Bootstrap is being able to build with their variables available so developers can stick to a convention and not have to name things on their own. Running the project requesting a very popular variable returns in an  error:
```
// styles.scss
ERROR in ./~/css-loader!./~/sass-loader!./src/ui/styles.scss
Module build failed:
  background-color: $brand-primary;
                   ^
      Undefined variable: "$brand-primary".
      in /Users/jb/Sites/forks/apollo-fullstack-starter-kit/src/ui/styles.scss (line 10, column 21)
Error:
  background-color: $brand-primary;
                   ^
      Undefined variable: "$brand-primary".
      in /Users/jb/Sites/forks/apollo-fullstack-starter-kit/src/ui/styles.scss (line 10, column 21)
    at options.error (/Users/jb/Sites/forks/apollo-fullstack-starter-kit/node_modules/node-sass/lib/index.js:291:26)
 @ ./src/ui/styles.scss 2:18-127 19:6-27:8 20:18-127
webpack-for-backend Time: 82ms
```
Unfortunately the only way to solve this is to import the bootstrap file within styles.scss to get access to the variables that Bootstrap already defined. I think the average developer looking at this repo will *probably* figure that out, but maybe a note should be made about this in the README. I do understand some developers want Bootstrap basics and don't care about variable access.

**Comment by vlasenko** [comment]
@josephdburdick Let's maybe merge styles.scss with bootstrap.scss then. Incremental build speedup time seems not worth the trouble and confusion it creates...
