### ISSUE TITLE
__DEV__ is false when running tests

### ISSUE THREAD

**Issue by yishaic** [sysgears/apollo-fullstack-starter-kit#35]
Hi,

First of all thanks for this great kit.

I'm starting to write tests, and saw that `__DEV__` is false when running `npm test`. This happens because of the line
`global.__DEV__ = process.argv.length >= 3 && process.argv[2] === 'watch';`

I've fixed it for now with
`global.__DEV__ = process.argv.length >= 3 && (process.argv[2] === 'watch' || process.argv[1].indexOf('mocha-webpack') >= 0);`
But I thought that maybe there is a better solution which should be applied.

**Comment by vlasenko** [comment]
I think your solution is fine. Please could you make Pull Request? Thanks!
