### ISSUE TITLE
If persistedQueries turned on, you still see all the queries in source

### ISSUE THREAD

**Issue by mitjade** [sysgears/apollo-fullstack-starter-kit#44]
If I take a look in the page source, you still see queries listed under:
`window.__APOLLO_STATE__=...`

Anything we can do about that?

**Comment by vlasenko** [comment]
I'm not sure. We need to investigate...

**Comment by vlasenko** [comment]
I have an idea. In `apollo_client.js` right now we do `__APOLLO_STATE__` cleaning:
```
    if (__CLIENT__) {
      if (window.__APOLLO_STATE__) {
        params.initialState = window.__APOLLO_STATE__;
        // Temporary workaround for bug in AC@0.5.0: https://github.com/apollostack/apollo-client/issues/845
        delete params.initialState.apollo.queries;
        delete params.initialState.apollo.mutations;
      }
      params.ssrForceFetchDelay = 100;
    }
```

Maybe we should clean up `__APOLLO_STATE__` on server side right before serialization instead? It should be better

**Comment by mitjade** [comment]
Let's try it out. Do not know exactly where to do this, could you try, or give me some pointers on how to accomplish this.

**Comment by vlasenko** [comment]
Done. Please check

**Comment by mitjade** [comment]
This is still shown as before:

```javascript
window.__APOLLO_STATE__={"counter":{"reduxCount":1},"apollo":{"data":{"$ROOT_QUERY.count":{"amount":5,"__typename":"Count"},"ROOT_QUERY":{"count":{"type":"id","id":"$ROOT_QUERY.count","generated":true}}},"optimistic":[],"reducerError":null},"routing":{"locationBeforeTransitions":null}};
```

**Comment by vlasenko** [comment]
@mitjade Yes, this is expected. This is queries data generated during Server Side Rendering. If you don't need server side rendering you can set `package.json` -> `ssr` to `false`

**Comment by mitjade** [comment]
ok
