### ISSUE TITLE
websockets_server.js obsolite?

### ISSUE THREAD

**Issue by mitjade** [sysgears/apollo-fullstack-starter-kit#47]
Is `src/server/websockets_server.js` obsolite?

If I delete it everything still seems to work.

**Comment by vlasenko** [comment]
No, it is not obsolete. The subscriptions will stop working if you delete it.

**Comment by mitjade** [comment]
Opened 2 browsers and tried it out. Still working..

**Comment by vlasenko** [comment]
@mitjade Yes you are right, actually subscriptions server is set up in `api_server.js`, so I think `websockets_server.js` is outdated indeed.

**Comment by mitjade** [comment]
Found this out by accident. Will create PR.

Am trying to add mqtt client so I would be able to publish mqtt events in mutations and still keep existing subscriptions, but can not seem to set it in a way to not have it restart on page reload or hot code reload, but still be able to expose client publish in schema.

I know this has nothing to do with this starter kit, but if you have any short pointers on how to archive this, would really appreciate it. If not np.

**Comment by vlasenko** [comment]
@mitjade I have no idea. If you could show me the code, that reveals the problem with hot code reload, I might be able to look when I will have time. I believe even making subscriptions in this starter kit to hot reload code changes in counter mutation code with restarting subscriptions might not be possible. Generally subscriptions might be hot code reload friendly first.

**Comment by mitjade** [comment]
Thx. Will prepare something in a fork, if I will not be able to figure this out.

**Comment by mitjade** [comment]
https://github.com/mitjade/apollo-fullstack-starter-kit/commit/cc3e95e70b8ae4c9693fb117900f602278ee8026

Here is an example of what I'm trying accomplish.

Start an MQTT client and subscribe to specific topics, which I managed to get working.

What I am not able to do, is to export a publish function in `src/server/api/mqtt_client.js` that I could then call when a certain Mutation is triggered.

If I call it as demonstrated in `src/server/api/schema.js`, if you press the '_Click to increase count_', I get an:
`error { TypeError: _mqtt_client2.default.publish is not a function`

I tried a few different approaches, all unsuccessful, so it looks like I still need to learn a few things on how javascript works...

**Comment by mitjade** [comment]
Second approach was:

`src/server/api/schema.js`
```javascript
...
  Mutation: {
    addCount(_, { amount }, context) {
      const client = mqttClient();
      client.publish('topic', 'message');
```

Here I get: 
`error { TypeError: Cannot read property 'on' of undefined`

**Comment by vlasenko** [comment]
Yes, you are certainly doing something wrong, why your `src/server/api/mqtt_client.js` closure has parameter `mqttClient`, e.g. `export default (mqttClient) =>`, where do you pass this parameter to your closure? You don't pass it at all

**Comment by vlasenko** [comment]
You should call your `mqtt_client.js` module like this:
`mqttClient(realMqttClientInstance).publish('topic', 'message');`

**Comment by mitjade** [comment]
How do I export the `mqttClient` instance from the `src/server/api_server.js` so I can access it in `src/server/api/schema.js`?

**Comment by mitjade** [comment]
`export default mqttClient;` in the `src/server/api_server.js`.

Sorry for a stupid question :) will try it out now.

**Comment by vlasenko** [comment]
I believe the way to do it is to use Apollo GraphQL context, see file `middleware/graphql.js` you should pass an instance of your mqttClient as parameter there, e.g.
```
app.use('/graphql', (...args) => graphqlMiddleware(mqttClient)(...args));
```

```
export default mqttClient => graphqlExpress(() => {
  return {
    schema,
    context: {
      Count: new Count(),
      mqttClient: mqttClient
    },
  };
});
```

And then in your GraphQL schema you will be able to access mqttClient

**Comment by mitjade** [comment]
Managed to get it working!

Thank you AGAIN for the help!!! I would probably keep banging my head agains the wall with this problem for quite a while. I guess I need to read up on some javascript fundamentals :)
