### ISSUE TITLE
How to publish an Array of sequelize object

### ISSUE THREAD

**Issue by jvallarvisp** [sysgears/apollo-fullstack-starter-kit#5]
Is this possible?

**Comment by vlasenko** [comment]
How is it related to this project? This starter kit doesn't use sequelize.

**Comment by jvallarvisp** [comment]
Hi @vlasenko, Thanks for your reply. What I did was that, I use sequelize instead of knex, I was able to integrated it. My question is that Is it possible to publish an Array of sequelize object? 
I was trying to create a publish-subscribe of my data from MySQL.

**Comment by vlasenko** [comment]
Hi,

I think this is possible, of course, but this question is out of scope of this starter kit. I would recommend you to ask the question about returning arrays from GraphQL subscriptions on StackOverflow.
