### ISSUE TITLE
Consider modularizing resolvers inside schema.js

### ISSUE THREAD

**Issue by josephdburdick** [sysgears/apollo-fullstack-starter-kit#54]
Hello, regarding the following block of code within `schema.js`, what is the path of least resistance to modularizing resolvers?
```
const resolvers = {
  Query: {
    count(ignored1, ignored2, context) {
      return context.Count.getCount();
    },
  },
  Mutation: {
    addCount(_, { amount }, context) {
      return context.Count.addCount(amount)
        .then(() => context.Count.getCount())
        .then(count => {
          pubsub.publish('countUpdated', count);
          return count;
        });
    },
  },
  Subscription: {
    countUpdated(amount) {
      return amount;
    }
  }
};
```
For larger projects the amount of queries, mutations, and subscriptions can make `schema.js` grow  a substantial amount, would you handle `resolvers` by importing it from another file or import the corresponding `Query`, `Mutation`, and `Subscription` items from another place? I find value in staying in sync with this repo so please share your thoughts. Thank you!

**Comment by vlasenko** [comment]
Hi, I think this section of the docs clarify the recommended approach pretty well, e.g. use something like lodash merge function for resolvers:
http://dev.apollodata.com/tools/graphql-tools/generate-schema.html#modularizing

**Comment by josephdburdick** [comment]
Yeah, you're right. Thanks for linking back to the docs, I've seen all that before but within this context it gave me a new perspective on the matter I hadn't considered before. Closing.

**Comment by mitjade** [comment]
Done something similar for post example [here](https://github.com/sysgears/apollo-fullstack-starter-kit/pull/95/commits/69a4ffb6a7b2f524f1153734835185d6f19312a4).
