### ISSUE TITLE
JS Assets not found when navigating to a nested route

### ISSUE THREAD

**Issue by josephdburdick** [sysgears/apollo-fullstack-starter-kit#59]
It appears Webpack doesn't properly resolve the location of assets when navigating to a nested route. This should be addressed as it means only routes at the top level will operate correctly.

This is what happens when running in **production** mode and you navigate from a top level location to a nested link:
<img width="827" alt="screen shot 2017-03-02 at 2 49 26 am" src="https://cloud.githubusercontent.com/assets/1349077/23494688/10a18e4e-fef3-11e6-904d-f6b022a2f6b5.png">

And this is what happens when you load a nested route in **development** mode:
<img width="833" alt="screen shot 2017-03-02 at 2 55 44 am" src="https://cloud.githubusercontent.com/assets/1349077/23494827/d305d774-fef3-11e6-848b-8f8379e5bfba.png">
When you click the bundle or vendor JS the console is reporting it returns the output above: all the markup needed to render a 404 HTML page inside both vendor.js and bundle.js.

**Comment by vlasenko** [comment]
@josephdburdick  Good catch! Please see the commit above, it should hopefully resolve this issue
