### ISSUE TITLE
Upgrade to apollo-client 0.5

### ISSUE THREAD

**Issue by mitjade** [sysgears/apollo-fullstack-starter-kit#6]
Any plans to up upgrade to apollo-client 0.5 package?

Tried it on my own but am running into some ssr problems. I keep getting:
"Apollo initial state may not contain queries, only data" error, which seems to be caused by ssr, but was not able to find the problem.

**Comment by vlasenko** [comment]
Yes, thanks for reminding. Hopefully I will update starter kit to 0.5 tonight.

Yes, this is a known bug in AC 0.5, there is a known workaround. Please do on client-side:
`delete window.__APOLLO_STATE__.apollo.queries`

**Comment by vlasenko** [comment]
This is the link to AC issue:
https://github.com/apollostack/apollo-client/issues/845
