### ISSUE TITLE
BREAKING: Run middleware and afterware only once per batched request

### ISSUE THREAD

**Issue by mitjade** [sysgears/apollo-fullstack-starter-kit#60]
Is this something that might concern this starter kit, since it now uses `apollo-client` 0.10.0?

I found `applyMiddleware` in `src/redux_store.js`, should this be now `applyBatchMiddleware `?

https://github.com/apollographql/apollo-client/pull/1285

**Comment by vlasenko** [comment]
@mitjade Thanks for pointing out this nuisance, however at the moment starter kit uses only `redux`'s applyMiddleware in `src/redux_store.js`, not apollo's one. So this issue is non-relevant for now.
