### ISSUE TITLE
"$NODE_ENV" was unexpected at this time. Error on npm install (windows)

### ISSUE THREAD

**Issue by aylabyuk** [sysgears/apollo-fullstack-starter-kit#63]
I am running on windows 10 with the latest node and npm but when I tried to npm install the package it produce an error **"$NODE_ENV" was unexpected at this time**. I have tried to install it on ubuntu and it works fine. It only happens on windows. Any ideas why?

**Comment by vlasenko** [comment]
Hi @aylabyuk,

Logs would be helpful, to understand whats happening

**Comment by vlasenko** [comment]
Though I bet the problem is caused by commands inside "scripts", e.g. by this construction:
```"start": "if [ \"$NODE_ENV\" = production ]; then ```

**Comment by aylabyuk** [comment]
sorry here is the log from npm-debug.log file 

here is the start of the error.

97 error Windows_NT 10.0.14393
98 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
99 error node v7.7.1
100 error npm  v4.1.2
101 error code ELIFECYCLE
102 error apollo-fullstack-starter-kit@1.0.0 postinstall: `if [ "$NODE_ENV" = production ]; then npm run clean && npm run build && npm run migrate && npm run seed; fi`
102 error Exit status 1
103 error Failed at the apollo-fullstack-starter-kit@1.0.0 postinstall script 'if [ "$NODE_ENV" = production ]; then npm run clean && npm run build && npm run migrate && npm run seed; fi'.
103 error Make sure you have the latest version of node.js and npm installed.
103 error If you do, this is most likely a problem with the apollo-fullstack-starter-kit package,
103 error not with npm itself.
103 error Tell the author that this fails on your system:
103 error     if [ "$NODE_ENV" = production ]; then npm run clean && npm run build && npm run migrate && npm run seed; fi
103 error You can get information on how to open an issue for this project with:
103 error     npm bugs apollo-fullstack-starter-kit
103 error Or if that isn't available, you can get their info via:
103 error     npm owner ls apollo-fullstack-starter-kit
103 error There is likely additional logging output above.
104 verbose exit [ 1, true ]

**Comment by vlasenko** [comment]
@aylabyuk I've pushed commit that might fix this issue. Unfortunately right now I can't test it under Windows. Could you try to update source code, try under Windows and report back?

**Comment by aylabyuk** [comment]
@vlasenko I have updated the code and run **npm install -save-dev if-env**. still have issue installing

here is the error log:

> 97 error Windows_NT 10.0.14393
98 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
99 error node v7.7.1
100 error npm  v4.1.2
101 error code ELIFECYCLE
102 error apollo-fullstack-starter-kit@1.0.0 postinstall: `if-env NODE_ENV=production && npm run clean && npm run build && npm run migrate && npm run seed`
102 error Exit status 1
103 error Failed at the apollo-fullstack-starter-kit@1.0.0 postinstall script 'if-env NODE_ENV=production && npm run clean && npm run build && npm run migrate && npm run seed'.
103 error Make sure you have the latest version of node.js and npm installed.
103 error If you do, this is most likely a problem with the apollo-fullstack-starter-kit package,
103 error not with npm itself.
103 error Tell the author that this fails on your system:
103 error     if-env NODE_ENV=production && npm run clean && npm run build && npm run migrate && npm run seed
103 error You can get information on how to open an issue for this project with:
103 error     npm bugs apollo-fullstack-starter-kit
103 error Or if that isn't available, you can get their info via:
103 error     npm owner ls apollo-fullstack-starter-kit
103 error There is likely additional logging output above.
104 verbose exit [ 1, true ]

**Comment by vlasenko** [comment]
I think now the scripts are Windows-friendly. Please clone the latest version of this repo and check.

**Comment by vlasenko** [comment]
Actually slightly changing Getting Started steps, I've managed to make scripts sections easier then it was, yet keeping them cross-platform.

**Comment by josephdburdick** [comment]
Perhaps instead of using an inline conditional statement there could be separate npm scripts and/or the use of `concurrently`. I think it would help alleviate ambiguity.

**Comment by vlasenko** [comment]
@josephdburdick I think right now it is done like you describe :) The `start` target has been split into `start` and `watch`. And instead of using `postinstall` for Heroku, now `heroku-postbuild` is utilized instead.

**Comment by josephdburdick** [comment]
_puts on 👓_

so it has! 👍

**Comment by vlasenko** [comment]
@aylabyuk Could you confirm, if it works for you or no?
