### ISSUE TITLE
Using static pages like landing page

### ISSUE THREAD

**Issue by GiladShoham** [sysgears/apollo-fullstack-starter-kit#7]
Hi,

First, thanks for your kit. It's a great job and saves me a lot of time!

I have some static pages (like landing / about / faq) which I believe should not be part of the main app (to reduce loading time).
Those pages currently are just plain HTMLs (no react), with CSS file and some vendors scripts.
I'm trying to somehow make those pages served but have problems in few places:

1. Web pack - Do you think it will be correct to make different bundles for this pages? for CSS/scripts. What is the correct way to do it?
2. Server side rendering - How do I handle this?
3. React router - Will I need to define those routes there? for example on /home? what will happen if I was already inside the app then click on the logo, for example, to go to the landing page, how will this work with react router?
4. vendor scripts - currently the scripts are just static scripts in the same folder, I'm thinking about using the npm versions instead, if not, maybe just keep the source directly as it is now and just make another bundle like landing.vender.js. but this also requires a lot of webpack work.

I thought about changing the website.jsx and check inside if I'm on the landing page then serve LandingHtml instead of HTML. but I'm not sure what will happen if then I'll try to go to login page from the client (because it will make client routing and this function won't call again, so I won't have the app) and same about the opposite (from app to homepage) also I'm not sure how does the index.jsx is connecting.

If you can help me and create some rough example of something like this (just example page with one h1 tag and one console.log and maybe jQuery as vendor), it will be great.

Maybe it's something you want to make in your kit anyway because I'm sure I'm not the only one who need this.

Thanks a lot.
Gilad.

**Comment by vlasenko** [comment]
Hi Gilad,

Thank you for giving a try to this starter kit.

Maybe what you are really looking for is code-splitting based on React routes, so that some React routes, that don't use heavy stuff like Apollo or  React Bootstrap didn't load these heavy dependencies and pulled only bare minimum needed? Like the way it is described here:
https://medium.com/@puppybits/webpack-code-splitting-by-routes-92f96cf733f2#.3zdulutcp

Yes, I think, that adding code-splitting support to this starter kit is a good idea and I will try to add this soon.

Victor

**Comment by GiladShoham** [comment]
Thanks for your quick response
Yes, code-splitting is my other thought about it.
I'm still thinking about which one is a better approach. 
Anyway, also configure a code-splitting is not so easy with all the different configs (SSR, dev/prod, vendors splitting, plain CSS vs sass) 
Also usually in the reality, a landing page will not use even react sometimes and not sass but only plain HTML/CSS with a script and some vendors script.
(Maybe the support should come in the form of a react component which use dangerouslySetInnerHTML to load the static HTML, in this case, it will support both react static page and HTML static page)
So a support for such case will be wonderfull.

By the way, what happen with code splitting when you make a client routing, like clicking on the logo to move to the landing page, because the splitting is on the server, and in client routing this mechanism won't run on the server, so somehow you have to load the additional required scripts. (I'm sure there is a solution for this, just wondering how it works)

Thanks again!

**Comment by vlasenko** [comment]
This issue needs more clarification, what do we really want. Closing it for now.
