### ISSUE TITLE
"Cannot find module 'apollo-client/errors"  (and how to fix it) 

### ISSUE THREAD

**Issue by jay-at-avido** [sysgears/apollo-fullstack-starter-kit#70]
We get this error when trying to run the code, unless  we install react-apollo dependency manually to have the correct version. (rc.2 instead of rc2)
The problem can be traced back the following issue ( and similar issues) reported on the react-apollo repo:

[https://github.com/apollographql/react-apollo/issues/524](https://github.com/apollographql/react-apollo/issues/524)

**Comment by jay-at-avido** [comment]
["Cannot find module 'apollo-client/errors"](url)

**Comment by vlasenko** [comment]
@jay-at-avido Yes, thanks for reporting and providing the workaround for Yarn. Let's hope the corresponding React Apollo issue will be fixed soon.

**Comment by vlasenko** [comment]
Okay. Please see my comments under this react-apollo issue. I think for now the way to go is to use `rc` prereleases of `react-apollo` in package.json explicitly, because yarn sorts releases in lexicographical order and this it correct behavior.
