### ISSUE TITLE
Webpack 2.3.1 does not compile, misconfigured output path

### ISSUE THREAD

**Issue by ChingxWando** [sysgears/apollo-fullstack-starter-kit#88]
Hey there,
First notice the issue itself as dev build does not compile. Which is not too complicated to resolve at all. I assume that it is simply due to new validations added to webpack 2.3.1 to ensure output.path to be a absolute path, see error messages below.

```
Using Webpack DLL vendor bundle
webpack-for-backend Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "build/server" is not an absolute path! WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "build/server" is not an absolute path!
```

Upon further investigation though, when I try putting together a small fix I noticed git is staging new files, server code bundles, under tools directory (will include client bundles too if in prod mode). This is probably due to somewhere in point the build scripts and config are moved from project root to tools folder causing the context to be wrong.
This looks like misconfiguration, probably the reason why webpack 2 now reinforce the use of absolute path for output.path now too. It makes the context of the project structure much easier to reason about.

**Comment by vlasenko** [comment]
@ChingxWando Please wait for 2 mins, I will take a look

**Comment by vlasenko** [comment]
@ChingxWando 
Please check, if the fix in the commit above works for you
