### ISSUE TITLE
rewire integration

### ISSUE THREAD

**Issue by GiladShoham** [sysgears/apollo-fullstack-starter-kit#91]
Hi,
Would be great to integrate [rewire](https://www.npmjs.com/package/rewire) (as a way to test private functions / vars)
It's a bit tricky with the es6 import/export and mocha webpack.

This might work:
https://www.npmjs.com/package/rewire-webpack
Or maybe this
https://github.com/speedskater/babel-plugin-rewire

What do you think?
Thanks.

**Comment by vlasenko** [comment]
Hi Gilad,

The first link want work, because it doesn't support Webpack 2. The babel plugin might work, but need to check this. It will be certainly tricky for ES6. Generally speaking if you need private function testing / private vars testing - you are doing something wrong, but I understand there might be exceptions and scenarios where this approach is valid...

**Comment by GiladShoham** [comment]
Hi,
Thanks, for the quick reply.

I have a service which fetches data from DB then do some manipulation.
The manipulation part is on a private function.
I want to test only this part (until I'll implement the full test with the DB fetching).

But even without this, there is always exceptions:)

By the way, I still haven't upgrade to webpack 2, so it might work:)

**Comment by vlasenko** [comment]
Hi,

Maybe approach like that in this answer might be more preferable (`rewire` seems as overkill for this purpose):
http://stackoverflow.com/questions/22097603/unit-testing-of-private-functions-with-mocha-and-node-js

**Comment by vlasenko** [comment]
This whole topic is controversal however :) If one would investigate compatibility of `rewire` with ES6 and if it is compatible indeed, then I think it's fine to add `rewire` to this kit as one of the approaches to test private functions.

**Comment by GiladShoham** [comment]
Ok,
I'll try to play a little bit with it.
If it will work I'll let you know.
If you do it before, just update the issue:)

**Comment by vlasenko** [comment]
@GiladShoham Sure, thank you Gilad!

**Comment by vlasenko** [comment]
Closing this, since not much activity happening and no clear plans when if we will work on it. Please reopen if you have another thoughts.
