### ISSUE TITLE
styled-components vs glamor?

### ISSUE THREAD

**Issue by j-jackson** [sysgears/apollo-fullstack-starter-kit#93]
This isn't really an issue, I was just curious why glamor over of styled-components?

its easy enough to replace for my own needs but I just wondered if there was a specific reason given that SC gives you the best of both.

**Comment by vlasenko** [comment]
@j-jackson I agree, styled-components would be a better choice. Would you be interested to submit a Pull Request that replaces glamor with styled-components?

**Comment by Morganjackson** [comment]
@vlasenko I have just created a new branch with SC (first PR so hopefully its ok!) but it looks like I need to be given access before I can create a PR.

**Comment by vlasenko** [comment]
@Morganjackson You should fork this repo, then you will be able to create branches on your copy of repo and then from these branches you can submit pull requests

**Comment by mitjade** [comment]
[Creating a pull request from a fork](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)

**Comment by vlasenko** [comment]
@j-jackson Seems `styled-components` do not support Server Side Rendering and hence it cannot be used in this starter kit until the support for SSR will be added:
https://github.com/styled-components/styled-components/issues/386

**Comment by vlasenko** [comment]
Seems alpha support for Server Side Rendering has been added to styled component, so it would be nice to research if we can use them in this starter kit as default CSS in JS implementation
