### ISSUE TITLE
XSS vulnerability in __APOLLO_STATE__

### ISSUE THREAD

**Issue by corydolphin** [sysgears/apollo-fullstack-starter-kit#96]
JSON.stringify is not XSS safe in HTML. It could contain eg. a </script> tag, which would allow an attacker to inject whatever they want into your page. 

See http://redux.js.org/docs/recipes/ServerRendering.html#inject-initial-component-html-and-state

**Comment by vlasenko** [comment]
@corydolphin I'm not quite following you, where is the XSS vulnerability?

`JSON.stringify` is executed server-side and produces string. This results in the following code executed client-side:
window.__APOLLO_STATE__ = 'some string'

What XSS vulnerability we have here?

**Comment by vlasenko** [comment]
@corydolphin Okay, I understand now. On client-side the code is actually:
`window.__APOLLO_STATE_ = {object definition}`

**Comment by mitjade** [comment]
Something seems to be wrong.

I get `Uncaught SyntaxError: Unexpected token {`, when starting...

**Comment by mitjade** [comment]
If I inspect html I see: 

`window.__APOLLO_STATE__=${&quot;apollo&quot; ... }}}`

**Comment by vlasenko** [comment]
@mitjade Okay, I have rewritten this commit

**Comment by mitjade** [comment]
Works now!

**Comment by vlasenko** [comment]
@corydolphin Many thanks for reporting this!
